version: '3.1'

services:
  db: 
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Gallery"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - db  

  app:
    build: 
        context: .
        dockerfile: Dockerfile
    container_name: gallery-backend
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    networks:
      - db  
    command: sh -c "npm run migration:run && npm run start:dev"

networks:
  db:
    driver: bridge